# Custom Language File for Launcher Customizer

[ejs.app]
title = "Maru Launcher"

[ejs.landing]
heroEyebrow = "MARU LAUNCHER"
heroTitle = "마루의 여름 계곡"
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/gimme-some/MaruLauncher"
supportLink = "https://github.com/gimme-some/MaruLauncher/issues"

[ejs.welcome]
welcomeHeader = "마루 런처에 오신 것을 환영합니다"
welcomeDescription = "마루 런처는 앞으로 열릴 마루 서버를 위한 전용 런처예요. 처음 실행하면 게임에 필요한 모드와 파일을 자동으로 내려받아 설정해 드립니다."
welcomeDescCTA = "몇 번의 클릭만으로 모험이 시작됩니다."
